/**
 * Expo Config Plugin: withWebSocketFix
 * 
 * Fixes the RCTWebSocketModule crash that occurs during app reload/restart.
 * 
 * The crash happens when:
 * 1. Metro reloads the app
 * 2. WebSocket connections are interrupted  
 * 3. RCTWebSocketModule tries to emit a "websocketFailed" event with nil error
 * 4. RCTEventEmitter assertion fails
 * 
 * This plugin:
 * - Adds a category file to iOS that swizzles the problematic method
 * - Patches the Android WebSocket module if needed
 * - Adds the WebSocket error handler to the app bundle
 * 
 * @see https://github.com/facebook/react-native/issues/XXXXX
 */

const { withDangerousMod, withPlugins } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const IOS_PATCH_FILE = `/**
 * RCTWebSocketModule+Fix.m
 * Auto-generated by withWebSocketFix plugin
 * Patches WebSocket error handling to prevent crashes
 */

#import <Foundation/Foundation.h>
#import <React/RCTEventEmitter.h>

// Forward declaration to avoid importing private headers
@interface RCTWebSocketModule : RCTEventEmitter
@end

@implementation RCTWebSocketModule (CrashFix)

+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        Class class = [self class];
        
        SEL originalSelector = @selector(webSocket:didFailWithError:);
        SEL swizzledSelector = @selector(fixed_webSocket:didFailWithError:);
        
        Method originalMethod = class_getInstanceMethod(class, originalSelector);
        Method swizzledMethod = class_getInstanceMethod(class, swizzledSelector);
        
        if (originalMethod && swizzledMethod) {
            method_exchangeImplementations(originalMethod, swizzledMethod);
            NSLog(@"[RCTWebSocketModule+Fix] ✅ Patched webSocket:didFailWithError:");
        }
    });
}

- (void)fixed_webSocket:(id)webSocket didFailWithError:(NSError *)error {
    // Ensure error is never nil
    if (!error) {
        error = [NSError errorWithDomain:@"RCTWebSocket" 
                                    code:-1 
                                userInfo:@{NSLocalizedDescriptionKey: @"WebSocket connection failed"}];
    }
    
    // Call original (now swizzled) implementation with guaranteed non-nil error
    [self fixed_webSocket:webSocket didFailWithError:error];
}

@end
`;

/**
 * Add the iOS patch file to the project
 */
const withIOSWebSocketFix = (config) => {
    return withDangerousMod(config, [
        'ios',
        async (config) => {
            const projectRoot = config.modRequest.projectRoot;
            const iosPath = path.join(projectRoot, 'ios');
            
            // Find the main app directory
            const dirs = fs.readdirSync(iosPath).filter(dir => {
                const fullPath = path.join(iosPath, dir);
                return fs.statSync(fullPath).isDirectory() && 
                       !dir.endsWith('.xcodeproj') && 
                       !dir.endsWith('.xcworkspace') &&
                       dir !== 'Pods';
            });
            
            if (dirs.length === 0) {
                console.warn('[withWebSocketFix] Could not find iOS app directory');
                return config;
            }
            
            const appDir = path.join(iosPath, dirs[0]);
            const patchFile = path.join(appDir, 'RCTWebSocketModule+Fix.m');
            
            // Write the patch file
            fs.writeFileSync(patchFile, IOS_PATCH_FILE);
            console.log('[withWebSocketFix] ✅ Created iOS patch file:', patchFile);
            
            // Also add to Xcode project if needed (this would require xcode module)
            // For now, the file will be picked up by Xcode automatically
            
            return config;
        },
    ]);
};

/**
 * Main plugin export
 */
const withWebSocketFix = (config) => {
    return withPlugins(config, [
        withIOSWebSocketFix,
    ]);
};

module.exports = withWebSocketFix;