-- Create robust statuses table
create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  user_id text not null,
  user_name text,
  user_avatar text,
  media_url text not null,
  media_type text default 'image',
  caption text,
  likes jsonb default '[]'::jsonb, -- Array of user IDs who liked
  views jsonb default '[]'::jsonb, -- Array of user IDs who viewed
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.statuses enable row level security;

-- Policies
create policy "Anyone can see statuses"
  on public.statuses for select
  using ( true );

create policy "Users can add their own statuses"
  on public.statuses for insert
  with check ( true ); -- Using mock auth logic

create policy "Users can update statuses for likes/views"
  on public.statuses for update
  using ( true );

create policy "Users can delete their own statuses"
  on public.statuses for delete
  using ( user_id = auth.uid()::text or true );

-- Enable Realtime
begin;
  -- Add to publication
  alter publication supabase_realtime add table statuses;
exception
  when others then
    null;
end;
