-- Create call_logs table for call history
create table public.call_logs (
  id bigint generated by default as identity primary key,
  caller_id text not null,
  callee_id text not null,
  call_type text check (call_type in ('audio', 'video')) not null,
  status text check (status in ('completed', 'missed', 'rejected', 'busy')) default 'completed',
  duration integer default 0, -- in seconds
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.call_logs enable row level security;

-- Policies
create policy "Users can see their own calls"
  on public.call_logs for select
  using ( caller_id = auth.uid()::text or callee_id = auth.uid()::text or true ); -- 'true' for mock auth

create policy "Users can insert calls"
  on public.call_logs for insert
  with check ( true ); 

-- Enable Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table public.profiles, public.call_logs, public.statuses, public.messages;
commit;
