-- Create messages table for chat
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender text not null,
  receiver text not null,
  text text not null,
  status text check (status in ('sent', 'delivered', 'read')) default 'sent',
  media_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.messages enable row level security;

-- Policies
create policy "Users can see their own messages"
  on public.messages for select
  using ( sender = auth.uid()::text or receiver = auth.uid()::text or true ); -- 'true' for mock auth

create policy "Users can insert messages"
  on public.messages for insert
  with check ( true ); 

create policy "Users can update their sent messages status"
  on public.messages for update
  using ( sender = auth.uid()::text or receiver = auth.uid()::text or true );

-- Ensure Realtime is enabled for the new table
begin;
  -- Add to publication if not already there
  alter publication supabase_realtime add table messages;
exception
  when others then
    -- Handle the case where it's already in the publication
    null;
end;
