-- ==============================================
-- SOULSYNC STATUSES - Complete Migration
-- This script creates the statuses table with all required columns
-- and enables real-time sync for cross-user status sharing
-- ==============================================

-- Drop existing table if it exists (to start fresh)
DROP TABLE IF EXISTS public.statuses CASCADE;

-- Create statuses table with ALL required columns
CREATE TABLE public.statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT,
  user_avatar TEXT,
  media_url TEXT NOT NULL,
  media_type TEXT DEFAULT 'image',
  caption TEXT,  -- This column is REQUIRED for status captions
  likes JSONB DEFAULT '[]'::JSONB,  -- Array of user IDs who liked
  views JSONB DEFAULT '[]'::JSONB,  -- Array of user IDs who viewed
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- Create index for faster queries
CREATE INDEX idx_statuses_user_id ON public.statuses(user_id);
CREATE INDEX idx_statuses_expires_at ON public.statuses(expires_at);
CREATE INDEX idx_statuses_created_at ON public.statuses(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.statuses ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- 1. Anyone can view active (non-expired) statuses
CREATE POLICY "Anyone can view active statuses"
  ON public.statuses FOR SELECT
  USING (expires_at > NOW());

-- 2. Authenticated users can insert their own statuses
CREATE POLICY "Users can insert their own statuses"
  ON public.statuses FOR INSERT
  WITH CHECK (TRUE);  -- Allow all inserts (mock auth compatible)

-- 3. Users can update statuses (for likes/views)
CREATE POLICY "Users can update statuses for likes and views"
  ON public.statuses FOR UPDATE
  USING (TRUE);  -- Allow all updates

-- 4. Users can delete their own statuses
CREATE POLICY "Users can delete their own statuses"
  ON public.statuses FOR DELETE
  USING (TRUE);  -- Allow all deletes (can be restricted later with auth.uid())

-- Enable Realtime for cross-user status sync
ALTER PUBLICATION supabase_realtime ADD TABLE public.statuses;

-- Create function to auto-delete expired statuses (optional cleanup)
CREATE OR REPLACE FUNCTION delete_expired_statuses()
RETURNS void AS $$
BEGIN
  DELETE FROM public.statuses WHERE expires_at < NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant necessary permissions
GRANT ALL ON public.statuses TO anon;
GRANT ALL ON public.statuses TO authenticated;
GRANT USAGE ON SEQUENCE statuses_id_seq TO anon;
GRANT USAGE ON SEQUENCE statuses_id_seq TO authenticated;

-- Verify table structure
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'statuses'
  AND table_schema = 'public'
ORDER BY ordinal_position;
