-- Create call_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.call_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caller_id TEXT NOT NULL,
  callee_id TEXT NOT NULL,
  call_type TEXT CHECK (call_type IN ('audio', 'video')) NOT NULL,
  status TEXT CHECK (status IN ('completed', 'missed', 'rejected', 'busy')) DEFAULT 'completed',
  duration INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.call_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Users can see their own calls" ON public.call_logs;
DROP POLICY IF EXISTS "Users can insert calls" ON public.call_logs;

-- Re-create Policies
CREATE POLICY "Users can see their own calls"
  ON public.call_logs FOR SELECT
  USING ( caller_id = auth.uid()::text OR callee_id = auth.uid()::text OR true );

CREATE POLICY "Users can insert calls"
  ON public.call_logs FOR INSERT
  WITH CHECK ( true );

-- Add to publication
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE public.profiles, public.call_logs, public.statuses, public.messages;
COMMIT;
